### ISSUE TITLE
Multiple responses  / keyword watcher

### ISSUE THREAD

**Issue by fommil** [Astrac/consierge#16]
As discussed in #15 it would be great if each repo had multiple responses each depending on some rule.

e.g. contributor points one word comment "wiki" it could post the boilerplate response about using the wiki.

**Comment by fommil** [comment]
also perhaps an option on each one to say if its active for tickets / pull requests (i just noticed our auto responder works on PRs too!)

**Comment by fommil** [comment]
I just had a crazy thought.... what if the responses were driven by the wiki! Maybe this is a devops matter (e.g. checking out the wiki repo to the right place) but it would be ace if the wiki were the source of the rules/responses. It wouldn't be too expensive to always get the latest rules and responses for each new comment / issue.

**Comment by ghost** [comment]
good idea. but can not find any API works with wiki.

**Comment by fommil** [comment]
It's available over git, also http. Regular polling is ok, its rare that these pages get updated so I'd be OK with hour/day delay.

**Comment by fommil** [comment]
But like mentioned, even on-demand would be fine for most projects
