### ISSUE TITLE
new name: consierge

### ISSUE THREAD

**Issue by fommil** [Astrac/consierge#17]
I believe @davegurnell suggested this as the name.

A lisp/functional programming pun on concierge (`cons`ierge... see, see!) and also that username / group name is available on github.

**Comment by fommil** [comment]
e.g. https://github.com/ensime/ensime-emacs/wiki/issue

(I actually saved this under `consierge/issue` on the checked out git, it seems to squash the names)

**Comment by davegurnell** [comment]
I think it's a cool name. The comedy spelling may be more trouble than it's
worth, but I'm willing to roll with it :)

Dave

**Comment by Astrac** [comment]
Sounds good to me as well, should we create a new repository with the new name and maybe under another organisation?

Sorry, didn't think of the most obvious thing, renaming it from _Settings_

**Comment by Astrac** [comment]
Done!
