### ISSUE TITLE
possible to modify ticket with checklist?

### ISSUE THREAD

**Issue by fommil** [Astrac/consierge#18]
I created a template with a checklist on it, but it turns out that the reporter can't tick things off.

It might be nice to edit the user's original ticket and put a checklist at the top of things they have to do, so they can tick them off when they go.

Maybe this is starting to be "too complicated" but wouldn't this workflow be nice?
1. issue reported
2. checklist added, tag added (e.g. "Needs info"), response added by bot
3. user ticks off the items in the checklist and (maybe) adds some comments
4. when all items are checked off, "Needs info" is removed and tagged as "ready" for core dev attention. OR too much time passes and the ticket is closed as "zombied".

**Comment by Astrac** [comment]
I am not sure that it is possible to make the checklist tickable: I don't remember seeing any around on github and as far as I know it's just a simple list with special classes for ticked elements at the HTML level. 

If that's true I can see two ways we could implement such a feature:
- The issuer can use a keyword in the comments to tick elements of the list
- The administrator can use Links in the list pointing to some URL handled by consierge where it will trigger an edit on the comment.

I think that the first one is a bit more laborious but has the good thing that trigger the user to explain something in the comments; the second option instead is easier to use from the issuer but it's hard to think a way to ensure that the issuer is the person clicking the links.

It's interesting in general the idea of managing the state of the ticket!

**Comment by fommil** [comment]
if you own the checklist, you're allowed to tick it. So I think it just means changing the original reporter's issue to have a checklist in it.
